### ISSUE TITLE
最新版本无法分享

### ISSUE THREAD

**Issue by PageQwQ** [HaoduStudio/website#8]
每日手帐版本3.0.0 小天才
在编辑好一份文档后 我想要把这份文档分享给别人  但是点击分享后却只进入了当前分享的手帐 没有出现任何分享的地方

DailyNotes version 3.0.0 for 小天才
After editing a document, I want to share it with others, but when I click to share, I only enter the current shared journal, and there is no place to share

**Comment by HikaruQwQ** [comment]
我们已经收到类似问题的反馈，感谢您对每日手帐生态的支持。

但是您的反馈位置似乎有些问题，您可以在 [DailyNotes-V3](https://github.com/HaoduStudio/DailyNotes-V3) 仓库提交这个issues。**这个issues将被关闭。**
